### ISSUE TITLE
The README installation is in a different package.

### ISSUE THREAD

**Issue by ktym4a** [florian-lefebvre/astro-tailwind-config-viewer#1]
I'm not sure if `astro-dev-plugin-reboot` is correct, but this seems wrong.
If it is correct, you can close it.

https://github.com/florian-lefebvre/astro-tailwind-config-viewer/blob/main/package/README.md#installation

**Comment by florian-lefebvre** [comment]
Not sure to understand what the issue is 🤔. Is it about this integration or `astro-dev-plugin-reboot`? I know the latter is probably not working for many reasons so I won't look at it for reference 😅

**Comment by florian-lefebvre** [comment]
Forget what I just said, I just realized 😂
